export default {
    jsPlugins: ['@hapi/oxc-plugin', 'oxlint-plugin-eslint'],
    plugins: ['node', 'unicorn'],
    env: {
        builtin: true,
        node: true,
    },
    rules: {
        // Custom rules
        '@hapi/capitalize-modules': ['warn', 'global-scope-only'],
        '@hapi/for-loop': ['warn', { maxDepth: 3, startIterator: 'i' }],
        '@hapi/no-var': 'error',
        // '@hapi/scope-start': 'warn', // This rule conflicts with oxfmt for now
        '@hapi/no-arrowception': 'error',

        'no-constant-condition': 'error',
        'no-undef': ['error', { typeof: false }],
        'no-shadow': ['warn', { allow: ['err', 'done'] }],
        'no-unused-vars': [
            'warn',
            { vars: 'all', caughtErrors: 'all', varsIgnorePattern: '^internals$', args: 'none' },
        ],
        'no-eq-null': 'warn',
        'no-extend-native': 'warn',
        'no-redeclare': 'warn',
        'no-loop-func': 'warn',
        yoda: ['warn', 'never'],
        'sort-vars': 'warn',
        'no-array-constructor': 'error',
        eqeqeq: 'error',
        curly: ['error', 'all'],
        'no-eval': 'error',
        'no-else-return': 'error',
        'no-return-assign': 'error',
        'no-new-wrappers': 'error',
        'no-ex-assign': 'error',
        'prefer-const': ['error', { destructuring: 'all' }],
        'func-style': ['error', 'expression'],
        'no-unsafe-finally': 'error',
        'no-useless-computed-key': 'error',
        'require-await': 'error',
        'constructor-super': 'error',
        'no-caller': 'error',
        'no-const-assign': 'error',
        'no-dupe-class-members': 'error',
        'no-class-assign': 'warn',
        'no-this-before-super': 'error',
        'prefer-rest-params': 'error',
        'prefer-spread': 'error',
        'no-useless-call': 'error',
        'no-dupe-keys': 'error',
        'node/handle-callback-err': ['error', '^(e|err|error)$'],
        'unicorn/no-new-buffer': 'error',
        'node/no-new-require': 'error',
        'typescript/dot-notation': 'warn',
        'eslint/no-object-constructor': 'error',
        'eslint/no-new-native-nonconstructor': 'error',
        'typescript/consistent-return': 'off',
        'eslint/vars-on-top': 'off',
        'eslint/new-cap': 'off',
        'eslint/no-console': 'off',
        'eslint/no-empty': 'off',
        'eslint/no-global-assign': 'off',
        'unicorn/no-process-exit': 'off',
        'eslint/no-unused-expressions': 'off',
        'eslint/no-regex-spaces': 'off',
        'eslint/no-lonely-if': 'off',
        'eslint/no-sparse-arrays': 'error',

        // Unsupported
        'eslint-js/prefer-arrow-callback': 'error',
        'eslint-js/consistent-this': ['error', 'self'],
        'eslint-js/object-shorthand': ['error', 'properties'],
        'eslint-js/one-var': ['error', 'never'],
    },
};
